language: android # can be 'java' if there is no android build target
android:
  components:
  - build-tools-20.0.0
  - android-20
jdk: oraclejdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1

# Setup environment
before_install:
- chmod +x gradlew

# Default gradle task will be run automatically on build, no need to define it

before_deploy:
# Generate a packaged jar for the desktop-project and rename it to include the tag
- ./gradlew desktop:dist
- mv desktop/build/libs/desktop-1.0.jar desktop/build/libs/Catacomb-Snatch-$TRAVIS_TAG.jar
# Generate a packaged apk for the android-project and rename it (this apk is unsigned/unaligned)
- ./gradlew android:assembleRelease
- mv android/build/outputs/apk/android-release-unsigned.apk android/build/outputs/apk/Catacomb-Snatch-$TRAVIS_TAG-unaligned.apk
# Generate and zip deployment files for the HTML project
- ./gradlew html:dist
- zip -r Catacomb-Snatch-$TRAVIS_TAG.zip ./html/build/dist/
deploy:
  provider: releases
  api_key:
    secure: O0udMd1RmlnP4dPvSyiIkbFMh0HI9UV2vsJSvSo91nSzsFS4U8FHYA9NUtbzqxtqs9JUZ2dbGwvJEjCYw7EzxaI02FbDjUfh6wGqHF3ZHUvjB5YO4V9g5IEURnl8om/JfBWvm4HkEijFBV/pJlsKzoPQUebBxFrLdV6vqcXOZMY=
  file:
  # Define which files should be deployed to GitHub
  - desktop/build/libs/Catacomb-Snatch-$TRAVIS_TAG.jar
  - android/build/outputs/apk/Catacomb-Snatch-$TRAVIS_TAG-unaligned.apk
  - Catacomb-Snatch-$TRAVIS_TAG.zip
  on:
    tag: true
    repo: Catacomb-Snatch/Catacomb-Snatch
    branches: master
    condition: "$TRAVIS_TAG =~ ^v\d+\.\d+\.\d+.*$" # Only deploy tags that match something like v1.0.0